apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - default-deny.yaml
  - nest-api.yaml
  - nest-controller.yaml
  - nest-node-agent.yaml
  - nest-scheduler.yaml
  - nest-csi.yaml
  - nest-gateway.yaml
  - nest-dblb.yaml
