apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: nest-dblb
  namespace: nest
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: nest-dblb
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 5000
  egress:
    - to:
        - podSelector: {}
