//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DeepCopyObject implements runtime.Object for DataResource
func (in *DataResource) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DataResource) DeepCopy() *DataResource {
	if in == nil {
		return nil
	}
	out := new(DataResource)
	in.DeepCopyInto(out)
	return out
}

func (in *DataResource) DeepCopyInto(out *DataResource) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *DataResourceSpec) DeepCopyInto(out *DataResourceSpec) {
	*out = *in
	if in.Protocols != nil {
		in, out := &in.Protocols, &out.Protocols
		*out = make([]Protocol, len(*in))
		copy(*out, *in)
	}
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		*out = new(ResourceSize)
		**out = **in
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(TLSConfig)
		**out = **in
	}
	if in.SecretsBackend != nil {
		in, out := &in.SecretsBackend, &out.SecretsBackend
		*out = new(SecretsBackendRef)
		**out = **in
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(ReplicaConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Import != nil {
		in, out := &in.Import, &out.Import
		*out = new(ImportSpec)
		**out = **in
	}
	if in.External != nil {
		in, out := &in.External, &out.External
		*out = new(ExternalSpec)
		(*in).DeepCopyInto(*out)
	}
}

func (in *DataResourceStatus) DeepCopyInto(out *DataResourceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Endpoints != nil {
		in, out := &in.Endpoints, &out.Endpoints
		*out = new(ResourceEndpoints)
		**out = **in
	}
	if in.Health != nil {
		in, out := &in.Health, &out.Health
		*out = new(HealthSignal)
		**out = **in
	}
	if in.ProvisionedAt != nil {
		in, out := &in.ProvisionedAt, &out.ProvisionedAt
		*out = (*in).DeepCopy()
	}
}

func (in *ReplicaConfig) DeepCopyInto(out *ReplicaConfig) {
	*out = *in
	if in.Write != nil {
		in, out := &in.Write, &out.Write
		*out = new(ReplicaCountSpec)
		**out = **in
	}
	if in.Read != nil {
		in, out := &in.Read, &out.Read
		*out = new(ReplicaCountSpec)
		**out = **in
	}
}

// DeepCopyObject implements runtime.Object for DataResourceList
func (in *DataResourceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DataResourceList) DeepCopy() *DataResourceList {
	if in == nil {
		return nil
	}
	out := new(DataResourceList)
	in.DeepCopyInto(out)
	return out
}

func (in *DataResourceList) DeepCopyInto(out *DataResourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DataResource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopyObject implements runtime.Object for DataResourceClass
func (in *DataResourceClass) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DataResourceClass) DeepCopy() *DataResourceClass {
	if in == nil {
		return nil
	}
	out := new(DataResourceClass)
	in.DeepCopyInto(out)
	return out
}

func (in *DataResourceClass) DeepCopyInto(out *DataResourceClass) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

func (in *ClassSpec) DeepCopyInto(out *ClassSpec) {
	*out = *in
	if in.Placement != nil {
		in, out := &in.Placement, &out.Placement
		*out = new(PlacementSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Replication != nil {
		in, out := &in.Replication, &out.Replication
		*out = new(ReplicationSpec)
		**out = **in
	}
	if in.Encryption != nil {
		in, out := &in.Encryption, &out.Encryption
		*out = new(EncryptionSpec)
		**out = **in
	}
	if in.SLO != nil {
		in, out := &in.SLO, &out.SLO
		*out = new(SLOSpec)
		**out = **in
	}
	if in.Cache != nil {
		in, out := &in.Cache, &out.Cache
		*out = new(CachePolicy)
		**out = **in
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(ReplicaConfig)
		(*in).DeepCopyInto(*out)
	}
}

func (in *PlacementSpec) DeepCopyInto(out *PlacementSpec) {
	*out = *in
	if in.Prefer != nil {
		in, out := &in.Prefer, &out.Prefer
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Allow != nil {
		in, out := &in.Allow, &out.Allow
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Forbid != nil {
		in, out := &in.Forbid, &out.Forbid
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopyObject implements runtime.Object for DataResourceClassList
func (in *DataResourceClassList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DataResourceClassList) DeepCopy() *DataResourceClassList {
	if in == nil {
		return nil
	}
	out := new(DataResourceClassList)
	in.DeepCopyInto(out)
	return out
}

func (in *DataResourceClassList) DeepCopyInto(out *DataResourceClassList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DataResourceClass, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopyObject implements runtime.Object for Tenant
func (in *Tenant) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *Tenant) DeepCopy() *Tenant {
	if in == nil {
		return nil
	}
	out := new(Tenant)
	in.DeepCopyInto(out)
	return out
}

func (in *Tenant) DeepCopyInto(out *Tenant) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *TenantSpec) DeepCopyInto(out *TenantSpec) {
	*out = *in
	if in.Quota != nil {
		in, out := &in.Quota, &out.Quota
		*out = new(QuotaSpec)
		**out = **in
	}
}

func (in *TenantStatus) DeepCopyInto(out *TenantStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopyObject implements runtime.Object for TenantList
func (in *TenantList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TenantList) DeepCopy() *TenantList {
	if in == nil {
		return nil
	}
	out := new(TenantList)
	in.DeepCopyInto(out)
	return out
}

func (in *TenantList) DeepCopyInto(out *TenantList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Tenant, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopyObject implements runtime.Object for HardwarePool
func (in *HardwarePool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *HardwarePool) DeepCopy() *HardwarePool {
	if in == nil {
		return nil
	}
	out := new(HardwarePool)
	in.DeepCopyInto(out)
	return out
}

func (in *HardwarePool) DeepCopyInto(out *HardwarePool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *HardwarePoolSpec) DeepCopyInto(out *HardwarePoolSpec) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

func (in *HardwarePoolStatus) DeepCopyInto(out *HardwarePoolStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopyObject implements runtime.Object for HardwarePoolList
func (in *HardwarePoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *HardwarePoolList) DeepCopy() *HardwarePoolList {
	if in == nil {
		return nil
	}
	out := new(HardwarePoolList)
	in.DeepCopyInto(out)
	return out
}

func (in *HardwarePoolList) DeepCopyInto(out *HardwarePoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HardwarePool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopyObject implements runtime.Object for HardwareInventory
func (in *HardwareInventory) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *HardwareInventory) DeepCopy() *HardwareInventory {
	if in == nil {
		return nil
	}
	out := new(HardwareInventory)
	in.DeepCopyInto(out)
	return out
}

func (in *HardwareInventory) DeepCopyInto(out *HardwareInventory) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *HardwareInventorySpec) DeepCopyInto(out *HardwareInventorySpec) {
	*out = *in
	if in.Devices != nil {
		in, out := &in.Devices, &out.Devices
		*out = make([]DeviceSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *DeviceSpec) DeepCopyInto(out *DeviceSpec) {
	*out = *in
	if in.SMART != nil {
		in, out := &in.SMART, &out.SMART
		*out = new(SMARTData)
		**out = **in
	}
}

func (in *HardwareInventoryStatus) DeepCopyInto(out *HardwareInventoryStatus) {
	*out = *in
	if in.LastScanTime != nil {
		in, out := &in.LastScanTime, &out.LastScanTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopyObject implements runtime.Object for HardwareInventoryList
func (in *HardwareInventoryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *HardwareInventoryList) DeepCopy() *HardwareInventoryList {
	if in == nil {
		return nil
	}
	out := new(HardwareInventoryList)
	in.DeepCopyInto(out)
	return out
}

func (in *HardwareInventoryList) DeepCopyInto(out *HardwareInventoryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HardwareInventory, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopyObject implements runtime.Object for Credential
func (in *Credential) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *Credential) DeepCopy() *Credential {
	if in == nil {
		return nil
	}
	out := new(Credential)
	in.DeepCopyInto(out)
	return out
}

func (in *Credential) DeepCopyInto(out *Credential) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *CredentialSpec) DeepCopyInto(out *CredentialSpec) {
	*out = *in
	if in.RotationPolicy != nil {
		in, out := &in.RotationPolicy, &out.RotationPolicy
		*out = new(RotationPolicy)
		**out = **in
	}
}

func (in *CredentialStatus) DeepCopyInto(out *CredentialStatus) {
	*out = *in
	if in.LastRotatedAt != nil {
		in, out := &in.LastRotatedAt, &out.LastRotatedAt
		*out = (*in).DeepCopy()
	}
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopyObject implements runtime.Object for CredentialList
func (in *CredentialList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *CredentialList) DeepCopy() *CredentialList {
	if in == nil {
		return nil
	}
	out := new(CredentialList)
	in.DeepCopyInto(out)
	return out
}

func (in *CredentialList) DeepCopyInto(out *CredentialList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Credential, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopyObject implements runtime.Object for DataProtectionPolicy
func (in *DataProtectionPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DataProtectionPolicy) DeepCopy() *DataProtectionPolicy {
	if in == nil {
		return nil
	}
	out := new(DataProtectionPolicy)
	in.DeepCopyInto(out)
	return out
}

func (in *DataProtectionPolicy) DeepCopyInto(out *DataProtectionPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

func (in *DataProtectionPolicySpec) DeepCopyInto(out *DataProtectionPolicySpec) {
	*out = *in
	if in.Snapshots != nil {
		in, out := &in.Snapshots, &out.Snapshots
		*out = new(SnapshotConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Backups != nil {
		in, out := &in.Backups, &out.Backups
		*out = new(BackupConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.PITR != nil {
		in, out := &in.PITR, &out.PITR
		*out = new(PITRConfig)
		**out = **in
	}
	if in.Verify != nil {
		in, out := &in.Verify, &out.Verify
		*out = new(VerifyConfig)
		(*in).DeepCopyInto(*out)
	}
}

func (in *SnapshotConfig) DeepCopyInto(out *SnapshotConfig) {
	*out = *in
	if in.Retention != nil {
		in, out := &in.Retention, &out.Retention
		*out = new(RetentionPolicy)
		**out = **in
	}
}

func (in *BackupConfig) DeepCopyInto(out *BackupConfig) {
	*out = *in
	if in.Destination != nil {
		in, out := &in.Destination, &out.Destination
		*out = new(BackupDestination)
		**out = **in
	}
	if in.CrossRegionCopy != nil {
		in, out := &in.CrossRegionCopy, &out.CrossRegionCopy
		*out = new(CrossRegionCopyConfig)
		**out = **in
	}
	if in.Retention != nil {
		in, out := &in.Retention, &out.Retention
		*out = new(RetentionPolicy)
		**out = **in
	}
}

func (in *VerifyConfig) DeepCopyInto(out *VerifyConfig) {
	*out = *in
	if in.RestoreTest != nil {
		in, out := &in.RestoreTest, &out.RestoreTest
		*out = new(RestoreTestConfig)
		**out = **in
	}
}

// DeepCopyObject implements runtime.Object for DataProtectionPolicyList
func (in *DataProtectionPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DataProtectionPolicyList) DeepCopy() *DataProtectionPolicyList {
	if in == nil {
		return nil
	}
	out := new(DataProtectionPolicyList)
	in.DeepCopyInto(out)
	return out
}

func (in *DataProtectionPolicyList) DeepCopyInto(out *DataProtectionPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DataProtectionPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopyObject implements runtime.Object for Schema
func (in *Schema) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *Schema) DeepCopy() *Schema {
	if in == nil {
		return nil
	}
	out := new(Schema)
	in.DeepCopyInto(out)
	return out
}

func (in *Schema) DeepCopyInto(out *Schema) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *SchemaSpec) DeepCopyInto(out *SchemaSpec) {
	*out = *in
	if in.Fields != nil {
		in, out := &in.Fields, &out.Fields
		*out = make([]SchemaField, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Indexes != nil {
		in, out := &in.Indexes, &out.Indexes
		*out = make([]SchemaIndex, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *SchemaField) DeepCopyInto(out *SchemaField) {
	*out = *in
	if in.Constraints != nil {
		in, out := &in.Constraints, &out.Constraints
		*out = make([]FieldConstraint, len(*in))
		copy(*out, *in)
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *SchemaIndex) DeepCopyInto(out *SchemaIndex) {
	*out = *in
	if in.Fields != nil {
		in, out := &in.Fields, &out.Fields
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *SchemaStatus) DeepCopyInto(out *SchemaStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopyObject implements runtime.Object for SchemaList
func (in *SchemaList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *SchemaList) DeepCopy() *SchemaList {
	if in == nil {
		return nil
	}
	out := new(SchemaList)
	in.DeepCopyInto(out)
	return out
}

func (in *SchemaList) DeepCopyInto(out *SchemaList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Schema, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopyObject implements runtime.Object for WebhookSubscription
func (in *WebhookSubscription) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *WebhookSubscription) DeepCopy() *WebhookSubscription {
	if in == nil {
		return nil
	}
	out := new(WebhookSubscription)
	in.DeepCopyInto(out)
	return out
}

func (in *WebhookSubscription) DeepCopyInto(out *WebhookSubscription) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *WebhookSubscriptionSpec) DeepCopyInto(out *WebhookSubscriptionSpec) {
	*out = *in
	if in.Events != nil {
		in, out := &in.Events, &out.Events
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *WebhookSubscriptionStatus) DeepCopyInto(out *WebhookSubscriptionStatus) {
	*out = *in
	if in.LastDeliveredAt != nil {
		in, out := &in.LastDeliveredAt, &out.LastDeliveredAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopyObject implements runtime.Object for WebhookSubscriptionList
func (in *WebhookSubscriptionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *WebhookSubscriptionList) DeepCopy() *WebhookSubscriptionList {
	if in == nil {
		return nil
	}
	out := new(WebhookSubscriptionList)
	in.DeepCopyInto(out)
	return out
}

func (in *WebhookSubscriptionList) DeepCopyInto(out *WebhookSubscriptionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WebhookSubscription, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopyObject implements runtime.Object for DarkDrive
func (in *DarkDrive) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DarkDrive) DeepCopy() *DarkDrive {
	if in == nil {
		return nil
	}
	out := new(DarkDrive)
	in.DeepCopyInto(out)
	return out
}

func (in *DarkDrive) DeepCopyInto(out *DarkDrive) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *DarkDriveSpec) DeepCopyInto(out *DarkDriveSpec) {
	*out = *in
	if in.SMART != nil {
		in, out := &in.SMART, &out.SMART
		*out = new(DarkDriveSMART)
		**out = **in
	}
}

func (in *DarkDriveSMART) DeepCopyInto(out *DarkDriveSMART) {
	*out = *in
}

func (in *DarkDriveStatus) DeepCopyInto(out *DarkDriveStatus) {
	*out = *in
	if in.ApprovedAt != nil {
		in, out := &in.ApprovedAt, &out.ApprovedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopyObject implements runtime.Object for DarkDriveList
func (in *DarkDriveList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DarkDriveList) DeepCopy() *DarkDriveList {
	if in == nil {
		return nil
	}
	out := new(DarkDriveList)
	in.DeepCopyInto(out)
	return out
}

func (in *DarkDriveList) DeepCopyInto(out *DarkDriveList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DarkDrive, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopyObject implements runtime.Object for Operation
func (in *Operation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *Operation) DeepCopy() *Operation {
	if in == nil {
		return nil
	}
	out := new(Operation)
	in.DeepCopyInto(out)
	return out
}

func (in *Operation) DeepCopyInto(out *Operation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *OperationSpec) DeepCopyInto(out *OperationSpec) {
	*out = *in
}

func (in *OperationStatus) DeepCopyInto(out *OperationStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.FinishedAt != nil {
		in, out := &in.FinishedAt, &out.FinishedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopyObject implements runtime.Object for OperationList
func (in *OperationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *OperationList) DeepCopy() *OperationList {
	if in == nil {
		return nil
	}
	out := new(OperationList)
	in.DeepCopyInto(out)
	return out
}

func (in *OperationList) DeepCopyInto(out *OperationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Operation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopyObject implements runtime.Object for NestFederation
func (in *NestFederation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *NestFederation) DeepCopy() *NestFederation {
	if in == nil {
		return nil
	}
	out := new(NestFederation)
	in.DeepCopyInto(out)
	return out
}

func (in *NestFederation) DeepCopyInto(out *NestFederation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *NestFederationSpec) DeepCopyInto(out *NestFederationSpec) {
	*out = *in
	if in.ResourceTypes != nil {
		in, out := &in.ResourceTypes, &out.ResourceTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Standbys != nil {
		in, out := &in.Standbys, &out.Standbys
		*out = make([]ClusterRef, len(*in))
		copy(*out, *in)
	}
	out.Primary = in.Primary
}

func (in *NestFederationStatus) DeepCopyInto(out *NestFederationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		copy(*out, *in)
	}
	if in.ClusterStatuses != nil {
		in, out := &in.ClusterStatuses, &out.ClusterStatuses
		*out = make([]ClusterStatus, len(*in))
		copy(*out, *in)
	}
}

func (in *NestFederationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *NestFederationList) DeepCopy() *NestFederationList {
	if in == nil {
		return nil
	}
	out := new(NestFederationList)
	in.DeepCopyInto(out)
	return out
}

func (in *NestFederationList) DeepCopyInto(out *NestFederationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NestFederation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopyObject implements runtime.Object for ComplianceBundle
func (in *ComplianceBundle) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ComplianceBundle) DeepCopy() *ComplianceBundle {
	if in == nil {
		return nil
	}
	out := new(ComplianceBundle)
	in.DeepCopyInto(out)
	return out
}

func (in *ComplianceBundle) DeepCopyInto(out *ComplianceBundle) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *ComplianceBundleSpec) DeepCopyInto(out *ComplianceBundleSpec) {
	*out = *in
}

func (in *ComplianceBundleStatus) DeepCopyInto(out *ComplianceBundleStatus) {
	*out = *in
	if in.Violations != nil {
		in, out := &in.Violations, &out.Violations
		*out = make([]PolicyViolation, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		copy(*out, *in)
	}
}

func (in *ComplianceBundleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ComplianceBundleList) DeepCopy() *ComplianceBundleList {
	if in == nil {
		return nil
	}
	out := new(ComplianceBundleList)
	in.DeepCopyInto(out)
	return out
}

func (in *ComplianceBundleList) DeepCopyInto(out *ComplianceBundleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ComplianceBundle, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopyObject implements runtime.Object for DataContract
func (in *DataContract) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DataContract) DeepCopy() *DataContract {
	if in == nil {
		return nil
	}
	out := new(DataContract)
	in.DeepCopyInto(out)
	return out
}

func (in *DataContract) DeepCopyInto(out *DataContract) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

func (in *DataContractSpec) DeepCopyInto(out *DataContractSpec) {
	*out = *in
	if in.Fields != nil {
		in, out := &in.Fields, &out.Fields
		*out = make([]DataContractField, len(*in))
		copy(*out, *in)
	}
}

// DeepCopyObject implements runtime.Object for DataContractList
func (in *DataContractList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DataContractList) DeepCopy() *DataContractList {
	if in == nil {
		return nil
	}
	out := new(DataContractList)
	in.DeepCopyInto(out)
	return out
}

func (in *DataContractList) DeepCopyInto(out *DataContractList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DataContract, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopyObject implements runtime.Object for ResourceLabel
func (in *ResourceLabel) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ResourceLabel) DeepCopy() *ResourceLabel {
	if in == nil {
		return nil
	}
	out := new(ResourceLabel)
	in.DeepCopyInto(out)
	return out
}

func (in *ResourceLabel) DeepCopyInto(out *ResourceLabel) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

func (in *ResourceLabelSpec) DeepCopyInto(out *ResourceLabelSpec) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopyObject implements runtime.Object for ResourceLabelList
func (in *ResourceLabelList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ResourceLabelList) DeepCopy() *ResourceLabelList {
	if in == nil {
		return nil
	}
	out := new(ResourceLabelList)
	in.DeepCopyInto(out)
	return out
}

func (in *ResourceLabelList) DeepCopyInto(out *ResourceLabelList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ResourceLabel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *BlockVolumeConfig) DeepCopyInto(out *BlockVolumeConfig) {
	*out = *in
}

func (in *BlockVolumeConfig) DeepCopy() *BlockVolumeConfig {
	if in == nil {
		return nil
	}
	out := new(BlockVolumeConfig)
	in.DeepCopyInto(out)
	return out
}

func (in *ObjectBucketConfig) DeepCopyInto(out *ObjectBucketConfig) {
	*out = *in
}

func (in *ObjectBucketConfig) DeepCopy() *ObjectBucketConfig {
	if in == nil {
		return nil
	}
	out := new(ObjectBucketConfig)
	in.DeepCopyInto(out)
	return out
}

func (in *ExternalSpec) DeepCopyInto(out *ExternalSpec) {
	*out = *in
	if in.BlockVolume != nil {
		in, out := &in.BlockVolume, &out.BlockVolume
		*out = new(BlockVolumeConfig)
		**out = **in
	}
	if in.ObjectBucket != nil {
		in, out := &in.ObjectBucket, &out.ObjectBucket
		*out = new(ObjectBucketConfig)
		**out = **in
	}
	if in.Extra != nil {
		in, out := &in.Extra, &out.Extra
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

func (in *ExternalSpec) DeepCopy() *ExternalSpec {
	if in == nil {
		return nil
	}
	out := new(ExternalSpec)
	in.DeepCopyInto(out)
	return out
}
