replicaCount: 1

image:
  repository: ghcr.io/penguintechinc/nest/data-indexer
  tag: ""
  pullPolicy: IfNotPresent

service:
  port: 8090

env:
  ADDR: ":8090"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
