apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nest
resources:
  - namespace.yaml
  - nest-api/deployment.yaml
  - nest-api/service.yaml
  - nest-controller/deployment.yaml
  - nest-controller/service.yaml
  - nest-node-agent/daemonset.yaml
  - nest-csi/daemonset.yaml
  - nest-csi/csidriver.yaml
  - nest-csi/storageclasses-cephfs.yaml
  - nest-scheduler/deployment.yaml
  - crds/dataprotectionpolicy.yaml
  - nest-rgw/objectstore.yaml
  - nest-rgw/service.yaml
  - nest-cephfs
  - nest-nfs-gateway/deployment.yaml
  - nest-nfs-gateway/service.yaml
  - nest-iscsi-gateway/deployment.yaml
  - nest-iscsi-gateway/service.yaml
  - nest-gateway/deployment.yaml
  - nest-gateway/service.yaml
  - nest-manager/deployment.yaml
  - nest-manager/service.yaml
