---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nest-cephfs
  labels:
    app.kubernetes.io/part-of: nest
provisioner: csi.nest.penguintech.io
parameters:
  clusterID: rook-ceph
  fsName: nest-cephfs
  pool: nest-cephfs-data0
  csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
  csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
  csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
  csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
  csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
  csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
  volumeType: cephfs
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate
mountOptions:
  - discard
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: nest-rbd-snapshot
  labels:
    app.kubernetes.io/part-of: nest
  annotations:
    snapshot.storage.kubernetes.io/is-default-class: "true"
driver: csi.nest.penguintech.io
deletionPolicy: Retain
parameters:
  clusterID: rook-ceph
  csi.storage.k8s.io/snapshotter-secret-name: rook-csi-rbd-provisioner
  csi.storage.k8s.io/snapshotter-secret-namespace: rook-ceph
  snapshotType: rbd
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: nest-cephfs-snapshot
  labels:
    app.kubernetes.io/part-of: nest
driver: csi.nest.penguintech.io
deletionPolicy: Retain
parameters:
  clusterID: rook-ceph
  csi.storage.k8s.io/snapshotter-secret-name: rook-csi-cephfs-provisioner
  csi.storage.k8s.io/snapshotter-secret-namespace: rook-ceph
  snapshotType: cephfs
