apiVersion: v1
kind: Service
metadata:
  name: nest-gateway
  labels:
    app: nest-gateway
    app.kubernetes.io/name: nest-gateway
    app.kubernetes.io/part-of: nest
spec:
  type: ClusterIP
  selector:
    app: nest-gateway
  ports:
  - name: grpc
    port: 50052
    targetPort: grpc
    protocol: TCP
  - name: http
    port: 8082
    targetPort: http
    protocol: TCP
