apiVersion: v1
kind: Service
metadata:
  name: nest-controller
  namespace: nest
  labels:
    app: nest-controller
    app.kubernetes.io/name: nest-controller
    app.kubernetes.io/part-of: nest
spec:
  type: ClusterIP
  selector:
    app: nest-controller
  ports:
  - name: health
    port: 8081
    targetPort: health
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: metrics
    protocol: TCP
