strimzi-kafka-operator:
  replicas: 1

  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

  # Beta: info logging level
  logLevel: INFO

  podDisruptionBudget:
    enabled: false
