apiVersion: v1
kind: Service
metadata:
  name: nest-cost-calculator
  labels:
    app: nest-cost-calculator
    app.kubernetes.io/name: nest-cost-calculator
    app.kubernetes.io/part-of: nest
spec:
  type: ClusterIP
  selector:
    app: nest-cost-calculator
  ports:
  - name: http
    port: 8091
    targetPort: http
    protocol: TCP
