cephCluster:
  mon:
    count: 3
  mgr:
    count: 2

filesystem:
  metadataServer:
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 2000m
        memory: 2Gi
