apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nest-node-agent
spec:
  template:
    spec:
      containers:
      - name: nest-node-agent
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 256Mi
        volumeMounts:
        - $patch: replace
        - name: dev
          mountPath: /dev
        - name: sys
          mountPath: /sys
        - name: proc
          mountPath: /proc
        - name: tmp
          mountPath: /tmp
      volumes:
      - $patch: replace
      - name: dev
        hostPath:
          path: /dev
          type: Directory
      - name: sys
        hostPath:
          path: /sys
          type: Directory
      - name: proc
        hostPath:
          path: /proc
          type: Directory
      - name: tmp
        emptyDir: {}
