apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nest-valkey.fullname" . }}-config
  labels:
    {{- include "nest-valkey.labels" . | nindent 4 }}
data:
  valkey.conf: |
    bind 0.0.0.0
    protected-mode no
    port {{ .Values.service.targetPort }}
    dir /data
    maxmemory {{ .Values.config.maxmemory }}
    maxmemory-policy {{ .Values.config.maxmemoryPolicy }}
    tcp-keepalive {{ .Values.config.tcpKeepalive }}
    timeout {{ .Values.config.timeout }}
    {{- if .Values.config.savePolicy }}
    save {{ .Values.config.savePolicy }}
    {{- else }}
    save ""
    {{- end }}
