{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nest-controller.serviceAccountName" . }}
  labels:
    {{- include "nest-controller.labels" . | nindent 4 }}
{{- end }}
