victoria-metrics-single:
  server:
    retentionPeriod: "24"
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 2000m
        memory: 2Gi
    persistentVolume:
      size: 200Gi
      storageClass: "nest-block"
