apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-scheduler
spec:
  replicas: 2
  template:
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - nest-scheduler
              topologyKey: kubernetes.io/hostname
      containers:
      - name: nest-scheduler
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
