apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-api
spec:
  replicas: 3
  template:
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - nest-api
              topologyKey: kubernetes.io/hostname
      containers:
      - name: nest-api
        env:
        - name: GIN_MODE
          value: "release"
        - name: LOG_LEVEL
          value: "warn"
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
