apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: nest
  labels:
    app: postgres
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: nest
spec:
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  type: ClusterIP
