apiVersion: v2
name: nest-rgw
description: Nest Ceph Object Store (Rados Gateway) for S3-compatible object storage
type: application
version: 0.1.0
appVersion: "0.1.0"
home: https://github.com/penguintechinc/nest
sources:
  - https://github.com/penguintechinc/nest
maintainers:
  - name: PenguinTech
    email: devops@penguintech.io
