apiVersion: v1
kind: Service
metadata:
  name: manager
  labels:
    app: manager
    app.kubernetes.io/name: manager
    app.kubernetes.io/part-of: nest
spec:
  type: ClusterIP
  selector:
    app: manager
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
