apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nest-iscsi-gateway.fullname" . }}-config
  labels:
    {{- include "nest-iscsi-gateway.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
