{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nest-iscsi-gateway.serviceAccountName" . }}
  labels:
    {{- include "nest-iscsi-gateway.labels" . | nindent 4 }}
{{- end }}
