altinity-clickhouse-operator:
  operator:
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 250m
        memory: 128Mi

  # Alpha: disable metrics exporter sidecar for minimal resource usage
  metrics:
    enabled: false

  serviceMonitor:
    enabled: false
