altinity-clickhouse-operator:
  operator:
    resources:
      requests:
        cpu: 200m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi

  # Beta: enable metrics exporter sidecar for observability
  metrics:
    enabled: true

  serviceMonitor:
    enabled: true
