apiVersion: v1
kind: Service
metadata:
  name: nest-web
  namespace: nest
  labels:
    app: nest-web
    app.kubernetes.io/name: nest-web
    app.kubernetes.io/part-of: nest
spec:
  type: ClusterIP
  selector:
    app: nest-web
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
