apiVersion: v2
name: nest-otel-collector
description: OpenTelemetry Collector for Nest
type: application
version: 1.0.0
appVersion: "0.115.1"
dependencies:
  - name: opentelemetry-collector
    version: "0.110.1"
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
