apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: {{ .Values.objectStore.name }}
  namespace: {{ .Values.objectStore.namespace }}
  labels:
    {{- include "nest-rgw.labels" . | nindent 4 }}
spec:
  metadataPool:
    {{- toYaml .Values.objectStore.metadataPool | nindent 4 }}
  dataPool:
    {{- toYaml .Values.objectStore.dataPool | nindent 4 }}
  preservePoolsOnDelete: {{ .Values.objectStore.preservePoolsOnDelete }}
  gateway:
    sslCertificateRef: {{ .Values.objectStore.gateway.sslCertificateRef }}
    port: {{ .Values.objectStore.gateway.port }}
    securePort: {{ .Values.objectStore.gateway.securePort }}
    instances: {{ .Values.objectStore.gateway.instances }}
    {{- if .Values.objectStore.gateway.resources }}
    resources:
      {{- toYaml .Values.objectStore.gateway.resources | nindent 6 }}
    {{- end }}
  {{- if .Values.objectStore.security }}
  security:
    {{- toYaml .Values.objectStore.security | nindent 4 }}
  {{- end }}
