replicaCount: 1

image:
  repository: ghcr.io/penguintechinc/nest/audit-service
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8085

env:
  ENTERPRISE_LICENSE: ""
  AUDIT_RETENTION_DAYS: "90"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

nodeSelector: {}

tolerations: []

affinity: {}
