apiVersion: v2
name: nest-mariadb-operator
description: MariaDB Operator for Nest database provisioning
type: application
version: 0.1.0
appVersion: "0.31.0"
dependencies:
  - name: mariadb-operator
    version: "0.31.0"
    repository: https://mariadb-operator.github.io/mariadb-operator
