mariadb-operator:
  metrics:
    enabled: true
  webhook:
    enabled: true
  certController:
    enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
