# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: config.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 7, 35, 0, "", "config.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0c\x63onfig.proto\x12\x0fnest.dbproxy.v1";\n\x10GetConfigRequest\x12\x13\n\x0b\x61pi_version\x18\x01 \x01(\t\x12\x12\n\nconfig_key\x18\x02 \x01(\t"d\n\x11GetConfigResponse\x12\x13\n\x0b\x61pi_version\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x15\n\rerror_message\x18\x03 \x01(\t\x12\x13\n\x0b\x63onfig_data\x18\x04 \x01(\x0c"P\n\x10SetConfigRequest\x12\x13\n\x0b\x61pi_version\x18\x01 \x01(\t\x12\x12\n\nconfig_key\x18\x02 \x01(\t\x12\x13\n\x0b\x63onfig_data\x18\x03 \x01(\x0c"O\n\x11SetConfigResponse\x12\x13\n\x0b\x61pi_version\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x15\n\rerror_message\x18\x03 \x01(\t"*\n\x13ReloadConfigRequest\x12\x13\n\x0b\x61pi_version\x18\x01 \x01(\t"l\n\x14ReloadConfigResponse\x12\x13\n\x0b\x61pi_version\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x15\n\rerror_message\x18\x03 \x01(\t\x12\x18\n\x10reload_timestamp\x18\x04 \x01(\t"\'\n\x10GetStatusRequest\x12\x13\n\x0b\x61pi_version\x18\x01 \x01(\t"\xbb\x01\n\x11GetStatusResponse\x12\x13\n\x0b\x61pi_version\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x1a\n\x12\x61\x63tive_connections\x18\x03 \x01(\x03\x12\x19\n\x11total_connections\x18\x04 \x01(\x03\x12\x19\n\x11queries_processed\x18\x05 \x01(\x03\x12\x17\n\x0fqueries_blocked\x18\x06 \x01(\x03\x12\x16\n\x0euptime_seconds\x18\x07 \x01(\t2\xe8\x02\n\rConfigService\x12R\n\tGetConfig\x12!.nest.dbproxy.v1.GetConfigRequest\x1a".nest.dbproxy.v1.GetConfigResponse\x12R\n\tSetConfig\x12!.nest.dbproxy.v1.SetConfigRequest\x1a".nest.dbproxy.v1.SetConfigResponse\x12[\n\x0cReloadConfig\x12$.nest.dbproxy.v1.ReloadConfigRequest\x1a%.nest.dbproxy.v1.ReloadConfigResponse\x12R\n\tGetStatus\x12!.nest.dbproxy.v1.GetStatusRequest\x1a".nest.dbproxy.v1.GetStatusResponseBLZJgithub.com/penguintechinc/nest/services/db-proxy/proto/dbproxyv1;dbproxyv1b\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "config_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals[
        "DESCRIPTOR"
    ]._serialized_options = (
        b"ZJgithub.com/penguintechinc/nest/services/db-proxy/proto/dbproxyv1;dbproxyv1"
    )
    _globals["_GETCONFIGREQUEST"]._serialized_start = 33
    _globals["_GETCONFIGREQUEST"]._serialized_end = 92
    _globals["_GETCONFIGRESPONSE"]._serialized_start = 94
    _globals["_GETCONFIGRESPONSE"]._serialized_end = 194
    _globals["_SETCONFIGREQUEST"]._serialized_start = 196
    _globals["_SETCONFIGREQUEST"]._serialized_end = 276
    _globals["_SETCONFIGRESPONSE"]._serialized_start = 278
    _globals["_SETCONFIGRESPONSE"]._serialized_end = 357
    _globals["_RELOADCONFIGREQUEST"]._serialized_start = 359
    _globals["_RELOADCONFIGREQUEST"]._serialized_end = 401
    _globals["_RELOADCONFIGRESPONSE"]._serialized_start = 403
    _globals["_RELOADCONFIGRESPONSE"]._serialized_end = 511
    _globals["_GETSTATUSREQUEST"]._serialized_start = 513
    _globals["_GETSTATUSREQUEST"]._serialized_end = 552
    _globals["_GETSTATUSRESPONSE"]._serialized_start = 555
    _globals["_GETSTATUSRESPONSE"]._serialized_end = 742
    _globals["_CONFIGSERVICE"]._serialized_start = 745
    _globals["_CONFIGSERVICE"]._serialized_end = 1105
# @@protoc_insertion_point(module_scope)
