# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import config_pb2 as config__pb2
import grpc

GRPC_GENERATED_VERSION = "1.82.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in config_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class ConfigServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetConfig = channel.unary_unary(
            "/nest.dbproxy.v1.ConfigService/GetConfig",
            request_serializer=config__pb2.GetConfigRequest.SerializeToString,
            response_deserializer=config__pb2.GetConfigResponse.FromString,
            _registered_method=True,
        )
        self.SetConfig = channel.unary_unary(
            "/nest.dbproxy.v1.ConfigService/SetConfig",
            request_serializer=config__pb2.SetConfigRequest.SerializeToString,
            response_deserializer=config__pb2.SetConfigResponse.FromString,
            _registered_method=True,
        )
        self.ReloadConfig = channel.unary_unary(
            "/nest.dbproxy.v1.ConfigService/ReloadConfig",
            request_serializer=config__pb2.ReloadConfigRequest.SerializeToString,
            response_deserializer=config__pb2.ReloadConfigResponse.FromString,
            _registered_method=True,
        )
        self.GetStatus = channel.unary_unary(
            "/nest.dbproxy.v1.ConfigService/GetStatus",
            request_serializer=config__pb2.GetStatusRequest.SerializeToString,
            response_deserializer=config__pb2.GetStatusResponse.FromString,
            _registered_method=True,
        )


class ConfigServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SetConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ReloadConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ConfigServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetConfig": grpc.unary_unary_rpc_method_handler(
            servicer.GetConfig,
            request_deserializer=config__pb2.GetConfigRequest.FromString,
            response_serializer=config__pb2.GetConfigResponse.SerializeToString,
        ),
        "SetConfig": grpc.unary_unary_rpc_method_handler(
            servicer.SetConfig,
            request_deserializer=config__pb2.SetConfigRequest.FromString,
            response_serializer=config__pb2.SetConfigResponse.SerializeToString,
        ),
        "ReloadConfig": grpc.unary_unary_rpc_method_handler(
            servicer.ReloadConfig,
            request_deserializer=config__pb2.ReloadConfigRequest.FromString,
            response_serializer=config__pb2.ReloadConfigResponse.SerializeToString,
        ),
        "GetStatus": grpc.unary_unary_rpc_method_handler(
            servicer.GetStatus,
            request_deserializer=config__pb2.GetStatusRequest.FromString,
            response_serializer=config__pb2.GetStatusResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "nest.dbproxy.v1.ConfigService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "nest.dbproxy.v1.ConfigService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class ConfigService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetConfig(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/nest.dbproxy.v1.ConfigService/GetConfig",
            config__pb2.GetConfigRequest.SerializeToString,
            config__pb2.GetConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def SetConfig(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/nest.dbproxy.v1.ConfigService/SetConfig",
            config__pb2.SetConfigRequest.SerializeToString,
            config__pb2.SetConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ReloadConfig(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/nest.dbproxy.v1.ConfigService/ReloadConfig",
            config__pb2.ReloadConfigRequest.SerializeToString,
            config__pb2.ReloadConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetStatus(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/nest.dbproxy.v1.ConfigService/GetStatus",
            config__pb2.GetStatusRequest.SerializeToString,
            config__pb2.GetStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
