apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nest
commonLabels:
  environment: beta
resources:
  - ../../base
replicas:
  - name: flask-backend
    count: 2
images:
  - name: nest/flask-backend
    newName: ghcr.io/penguintechinc/nest/flask-backend
    newTag: latest
configMapGenerator:
  - name: nest-config
    behavior: merge
    literals:
      - LOG_LEVEL=INFO
      - RELEASE_MODE=false
