apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "articdbm.fullname" . }}-proxy
  labels:
    {{- include "articdbm.labels" . | nindent 4 }}
    app.kubernetes.io/component: proxy
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "articdbm.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: proxy
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "articdbm.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: proxy
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "articdbm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: proxy
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.proxyImage.registry }}{{ if .Values.proxyImage.registry }}/{{ end }}{{ .Values.proxyImage.repository }}:{{ .Values.proxyImage.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.proxyImage.pullPolicy }}
        ports:
        - name: mysql
          containerPort: 3306
          protocol: TCP
        - name: postgres
          containerPort: 5432
          protocol: TCP
        - name: mssql
          containerPort: 1433
          protocol: TCP
        - name: mongodb
          containerPort: 27017
          protocol: TCP
        - name: redis-proxy
          containerPort: 6380
          protocol: TCP
        - name: metrics
          containerPort: 9090
          protocol: TCP
        envFrom:
        - configMapRef:
            name: {{ include "articdbm.fullname" . }}-config
        livenessProbe:
          tcpSocket:
            port: metrics
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: metrics
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          {{- toYaml .Values.resources.proxy | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
