apiVersion: v1
kind: Service
metadata:
  name: {{ include "articdbm.fullname" . }}-manager
  labels:
    {{- include "articdbm.labels" . | nindent 4 }}
    app.kubernetes.io/component: manager
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.managerPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "articdbm.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: manager
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "articdbm.fullname" . }}-proxy
  labels:
    {{- include "articdbm.labels" . | nindent 4 }}
    app.kubernetes.io/component: proxy
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.proxyMysqlPort }}
      targetPort: mysql
      protocol: TCP
      name: mysql
    - port: {{ .Values.service.proxyPostgresPort }}
      targetPort: postgres
      protocol: TCP
      name: postgres
    - port: {{ .Values.service.proxyMssqlPort }}
      targetPort: mssql
      protocol: TCP
      name: mssql
    - port: {{ .Values.service.proxyMongodbPort }}
      targetPort: mongodb
      protocol: TCP
      name: mongodb
    - port: {{ .Values.service.proxyRedisPort }}
      targetPort: redis-proxy
      protocol: TCP
      name: redis-proxy
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "articdbm.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: proxy
