{{- $op := index .Values "opensearch-operator" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nest-opensearch.fullname" . }}-operator
  labels:
    {{- include "nest-opensearch.labels" . | nindent 4 }}
spec:
  replicas: {{ $op.replicaCount }}
  selector:
    matchLabels:
      {{- include "nest-opensearch.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nest-opensearch.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "nest-opensearch.serviceAccountName" . }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: manager
        image: "{{ $op.image.repository }}:{{ $op.image.tag }}{{ if $op.image.digest }}@{{ $op.image.digest }}{{ end }}"
        imagePullPolicy: {{ $op.image.pullPolicy }}
        args:
          - "--leader-elect"
          {{- if $op.watchNamespaces }}
          - "--watch-namespaces={{ $op.watchNamespaces }}"
          {{- end }}
        env:
        - name: OPERATOR_LOG_LEVEL
          value: {{ $op.logLevel }}
        ports:
        - name: metrics
          containerPort: {{ $op.monitoring.metricsPort }}
          protocol: TCP
        - name: webhook
          containerPort: {{ $op.webhook.port }}
          protocol: TCP
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          {{- toYaml $op.manager.resources | nindent 12 }}
        volumeMounts:
        - name: webhook-cert
          mountPath: /tmp/k8s-webhook-server/serving-certs
          readOnly: true
      volumes:
      - name: webhook-cert
        secret:
          secretName: {{ include "nest-opensearch.fullname" . }}-webhook-cert
          optional: true
