{{- if .Values.opensearch-operator.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nest-opensearch.serviceAccountName" . }}
  labels:
    {{- include "nest-opensearch.labels" . | nindent 4 }}
{{- end }}
