loki:
  deploymentMode: SingleBinary
  loki:
    auth_enabled: false
    storage:
      type: filesystem
    commonConfig:
      replication_factor: 1
    limits_config:
      retention_period: 720h
  singleBinary:
    replicas: 1
    persistence:
      enabled: true
      size: 50Gi
  monitoring:
    dashboards:
      enabled: false
    rules:
      enabled: false
