apiVersion: v1
kind: Service
metadata:
  name: articdbm-manager
  labels:
    app.kubernetes.io/name: articdbm
    app.kubernetes.io/component: manager
    app.kubernetes.io/managed-by: kustomize
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: articdbm
    app.kubernetes.io/component: manager
