image:
  repository: localhost:32000/nest-controller
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

env:
  GIN_MODE: debug
  LOG_LEVEL: debug
